- 
  name: 'Install App Stack'
  hosts: target1
  roles:
    - role: my_tools
      tag:
        - tools
    - role: my_nginx
      tags: 
        - nginx
    - role: my_postgresql
      tags:
        - db